### ISSUE TITLE
Error: not found: python2

### ISSUE THREAD

**Issue by galinowski** [kbadk/gmvault-webreader#17]
`docker build . -t kbadk/gmvault-webreader` fails on my Mac mini M1 with the error 

`Error: Can't find Python executable "python", you can set the PYTHON env variable.`

The solution I found is to update Dockerfile:

`FROM node:14-slim`

with

```
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
```

**Comment by kbadk** [comment]
Hi, thank you for the report.

I'm not a big fan of downgrading to Node v12. I notice that `python2` doesn't exist in `node:14-alpine`, presumably why you downgraded to Node v12.

However, I was able to reproduce the error (on an ARM host, my Intel Mac builds just fine) and fix it with the below, while staying on `node:14-slim`:

```Dockerfile
RUN apt-get update && apt-get install -y \
	python g++ make \
	&& rm -rf /var/lib/apt/lists/*
```

I hope this solution also works for you.
